### ISSUE TITLE
MarkDups error processing hard-clipped supplementary alignments

### ISSUE THREAD

**Issue by scwatts** [nf-core/oncoanalyser#37]
MarkDups v1.1.5 may encounter an error processing hard-clipping supplementary alignments when forming consensus sequences.

This error can impact users where DNA alignment has been performed outside of oncoanalyser if supplementary alignments were hard-clipped rather than soft-clipped.

An example of relevant log messages with stack trace from the error:

```text
01:44:41.884 [Thread-4] [ERROR] error forming consensus: id(null) fragments(2) coords(chr1_4144412_R_chr1_4144584_N) readCounts(PRIMARY=0 complete, MATE=0 pending, MATE_SUPPLEMENTARY=2 ready)
01:44:41.884 [Thread-4] [ERROR] read: id(A00130:175:HGKJNDSX2:1:2271:14118:33646) coords(chr1:4144532-4144633) cigar(74M2D26M50H) mate(chr1:4144262) flags(2145)
01:44:41.885 [Thread-4] [ERROR] read: id(A00130:175:HGKJNDSX2:1:1565:9091:2268) coords(chr1:4144532-4144601) cigar(70M80H) mate(chr1:4144262) flags(2209)
java.lang.ArrayIndexOutOfBoundsException: Index 70 out of bounds for length 70
        at com.hartwig.hmftools.markdups.consensus.ReadParseState.currentBase(ReadParseState.java:53)
        at com.hartwig.hmftools.markdups.consensus.IndelConsensusReads.addElementBases(IndelConsensusReads.java:209)
        at com.hartwig.hmftools.markdups.consensus.IndelConsensusReads.buildIndelComponents(IndelConsensusReads.java:83)
        at com.hartwig.hmftools.markdups.consensus.ConsensusReads.createConsensusRead(ConsensusReads.java:130)
        at com.hartwig.hmftools.markdups.common.DuplicateGroup.popCompletedReads(DuplicateGroup.java:350)
        at com.hartwig.hmftools.markdups.PartitionReader.processDuplicateGroup(PartitionReader.java:321)
        at com.hartwig.hmftools.markdups.PartitionReader.lambda$processIncompleteRead$0(PartitionReader.java:250)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at com.hartwig.hmftools.markdups.PartitionReader.processIncompleteRead(PartitionReader.java:250)
        at com.hartwig.hmftools.markdups.PartitionReader.processSamRecord(PartitionReader.java:209)
        at com.hartwig.hmftools.markdups.BamReader.sliceRegion(BamReader.java:58)
        at com.hartwig.hmftools.markdups.PartitionReader.processRegion(PartitionReader.java:123)
        at com.hartwig.hmftools.markdups.PartitionThread.run(PartitionThread.java:61)
```

**Comment by bounlu** [comment]
I also had the same issue with version `1.1.7`:

```
Command error:
  Unable to find image 'quay.io/biocontainers/hmftools-mark-dups:1.1.7--hdfd78af_0' locally
  1.1.7--hdfd78af_0: Pulling from biocontainers/hmftools-mark-dups
  ca7680d1025d: Already exists
  bd9ddc54bea9: Already exists
  b5e822314cc7: Pulling fs layer
  b5e822314cc7: Verifying Checksum
  b5e822314cc7: Download complete
  b5e822314cc7: Pull complete
  Digest: sha256:9040ac4af8fb438148a50e03659407a3ccc1de88dfa6d424cb18eae38a330b2a
  Status: Downloaded newer image for quay.io/biocontainers/hmftools-mark-dups:1.1.7--hdfd78af_0
  /usr/local/bin/markdups: line 6: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
  09:12:13.026 [main] [INFO ] MarkDups version 1.1.7
  09:12:13.133 [main] [INFO ] output(./)
  09:12:13.351 [main] [INFO ] loaded 80309 unmapping regions from unmap_regions.38.tsv
  09:12:13.352 [main] [INFO ] duplicate logic: UMIs
  09:12:13.357 [main] [INFO ] sample(220024109) starting mark duplicates
  09:12:13.980 [Thread-0] [ERROR] read(id(F350034942L2C003R05000591155) coords(chr1:87313-87407) cigar(5S95M) mate(chr1:87376) flags(163)) exception: java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 28
  java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 28
  	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
  	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
  	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
  	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
  	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
  	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
  	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
  	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4914)
  	at java.base/java.lang.String.substring(String.java:2876)
  	at com.hartwig.hmftools.markdups.umi.UmiGroupBuilder.splitUmi(UmiGroupBuilder.java:505)
  	at com.hartwig.hmftools.markdups.umi.UmiGroupBuilder.hasDuplexUmiMatch(UmiGroupBuilder.java:493)
  	at com.hartwig.hmftools.markdups.umi.UmiGroupBuilder.collapseCoordinateGroup(UmiGroupBuilder.java:444)
  	at com.hartwig.hmftools.markdups.umi.UmiGroupBuilder.processUmiGroups(UmiGroupBuilder.java:289)
  	at com.hartwig.hmftools.markdups.common.DuplicateGroupBuilder.processDuplicateGroups(DuplicateGroupBuilder.java:248)
  	at com.hartwig.hmftools.markdups.PartitionReader.accept(PartitionReader.java:357)
  	at com.hartwig.hmftools.markdups.PartitionReader.accept(PartitionReader.java:43)
  	at com.hartwig.hmftools.markdups.ReadPositionsCache.checkFlush(ReadPositionsCache.java:305)
  	at com.hartwig.hmftools.markdups.ReadPositionsCache.storeInitialRead(ReadPositionsCache.java:166)
  	at com.hartwig.hmftools.markdups.ReadPositionsCache.processRead(ReadPositionsCache.java:141)
  	at com.hartwig.hmftools.markdups.PartitionReader.processSamRecord(PartitionReader.java:216)
  	at com.hartwig.hmftools.markdups.BamReader.sliceRegion(BamReader.java:83)
  	at com.hartwig.hmftools.markdups.PartitionReader.processRegion(PartitionReader.java:125)
  	at com.hartwig.hmftools.markdups.PartitionThread.run(PartitionThread.java:61)
```

**Comment by scwatts** [comment]
Thanks for the stack trace, this looks to be a slightly different error related to UMI processing rather than hard-clipping in supplementary alignments. Another user has reported the same error today as well.

The exact cause isn't immediately obvious to me, if you're able to share some of the data that triggers this error I can pass that onto the MarkDups developers to help fix/diagnose the problem.

Since it is a different error I'll close this issue. Can you open a new one to specifically track the new error you're describing?
