### ISSUE TITLE
`markdups` fails with `Range [0, -1) out of bounds` error

### ISSUE THREAD

**Issue by bounlu** [nf-core/oncoanalyser#99]
Referring to https://github.com/nf-core/oncoanalyser/issues/37#issuecomment-2230479616

Nextflow run:
```
#!/bin/bash

nextflow run nf-core/oncoanalyser \
-latest \
-profile docker \
--mode 'targeted' \
--genome 'GRCh38_hmf' \
--panel 'tso500' \
--input 'samplesheet_oncoanalyser.csv' \
--outdir 'oncoanalyser/results/' \
-work-dir 'oncoanalyser/work/' \
-c 'custom_local.config' \
-r master \
-resume
```

```
Unable to find image 'quay.io/biocontainers/hmftools-mark-dups:1.1.7--hdfd78af_0' locally
1.1.7--hdfd78af_0: Pulling from biocontainers/hmftools-mark-dups
ca7680d1025d: Already exists
bd9ddc54bea9: Already exists
b5e822314cc7: Pulling fs layer
b5e822314cc7: Verifying Checksum
b5e822314cc7: Download complete
b5e822314cc7: Pull complete
Digest: sha256:9040ac4af8fb438148a50e03659407a3ccc1de88dfa6d424cb18eae38a330b2a
Status: Downloaded newer image for quay.io/biocontainers/hmftools-mark-dups:1.1.7--hdfd78af_0
/usr/local/bin/markdups: line 6: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
06:00:24.766 [main] [INFO ] MarkDups version 1.1.7
06:00:24.826 [main] [INFO ] output(./)
06:00:25.171 [main] [INFO ] loaded 80309 unmapping regions from unmap_regions.38.tsv
06:00:25.172 [main] [INFO ] duplicate logic: UMIs
06:00:25.174 [main] [INFO ] sample(220024466) starting mark duplicates
06:00:26.293 [Thread-0] [ERROR] read(id(F350034942L2C002R05300375863) coords(chr1:45099-45194) cigar(4S96M) mate(chr1:45147) flags(99)) exception: java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 28
java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 28
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4914)
	at java.base/java.lang.String.substring(String.java:2876)
	at com.hartwig.hmftools.markdups.umi.UmiGroupBuilder.splitUmi(UmiGroupBuilder.java:505)
	at com.hartwig.hmftools.markdups.umi.UmiGroupBuilder.hasDuplexUmiMatch(UmiGroupBuilder.java:493)
	at com.hartwig.hmftools.markdups.umi.UmiGroupBuilder.collapseCoordinateGroup(UmiGroupBuilder.java:444)
	at com.hartwig.hmftools.markdups.umi.UmiGroupBuilder.processUmiGroups(UmiGroupBuilder.java:289)
	at com.hartwig.hmftools.markdups.common.DuplicateGroupBuilder.processDuplicateGroups(DuplicateGroupBuilder.java:248)
	at com.hartwig.hmftools.markdups.PartitionReader.accept(PartitionReader.java:357)
	at com.hartwig.hmftools.markdups.PartitionReader.accept(PartitionReader.java:43)
	at com.hartwig.hmftools.markdups.ReadPositionsCache.checkFlush(ReadPositionsCache.java:305)
	at com.hartwig.hmftools.markdups.ReadPositionsCache.storeInitialRead(ReadPositionsCache.java:166)
	at com.hartwig.hmftools.markdups.ReadPositionsCache.processRead(ReadPositionsCache.java:141)
	at com.hartwig.hmftools.markdups.PartitionReader.processSamRecord(PartitionReader.java:216)
	at com.hartwig.hmftools.markdups.BamReader.sliceRegion(BamReader.java:83)
	at com.hartwig.hmftools.markdups.PartitionReader.processRegion(PartitionReader.java:125)
	at com.hartwig.hmftools.markdups.PartitionThread.run(PartitionThread.java:61)
```

I would suggest to use a more established tool like [Picard MarkDuplicates](https://gatk.broadinstitute.org/hc/en-us/articles/360037052812-MarkDuplicates-Picard) to avoid such cases.

**Comment by scwatts** [comment]
Hi @bounlu, the Hartwig MarkDups tool is preferred since it uses algorithm optimised for the Hartwig toolkit and runs additional routines beyond duplicate marking. I understand your perspective however.

To help investigate this issue, would you be able share the .nextflow.log associated with the above error and a couple of reads (or alignments) that shows your UMI data?

**Comment by bounlu** [comment]
Unfortunately I can't share the log files for safety reasons. Regarding the reads, however, I can tell that I am testing the pipeline with our custom targeted panel but choosing `tso500` in the parameters just to see how it works. Do you think this may cause the above issue?

**Comment by scwatts** [comment]
The current processing of UMIs in oncoanalyser is:

1. extract UMIs from FASTQ read sequence and place into read name with fastp
1. align reads using bwa-mem2
1. call consensus and mark duplicates with MarkDups

I'm working on better support for various UMI structures, which will be facilitated by the [fastp options](https://github.com/OpenGene/fastp?tab=readme-ov-file#unique-molecular-identifier-umi-processing). Further details on the MarkDups algorithm are available [here](https://github.com/hartwigmedical/hmftools/tree/mark-dups-v1.1.7/mark-dups).

**Comment by bounlu** [comment]
For `fastp`, I need to use the below parameters:

`fastp -U --umi_loc=per_read --umi_len=7`

Could you please point me where can I specify these options in the pipeline?

**Comment by scwatts** [comment]
In the [0.5.0 release](https://github.com/nf-core/oncoanalyser/tree/0.5.0) you can achieve that configuration by setting `--umi_length 7` for the oncoanalyser command.

I'm working on an enhancement that will allow more flexible configuration of UMI processing in fastp and MarkDups, the above will change slightly once those adjustments have been made in the `dev` branch.

**Comment by bounlu** [comment]
Adding `--umi_length 7` to `fastp` adds the UMIs to the read IDs, however, `mark-dups` still fails:

```
-[nf-core/oncoanalyser] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_ONCOANALYSER:TARGETED:READ_PROCESSING:MARKDUPS (220024489_220024489)'

Caused by:
  Process `NFCORE_ONCOANALYSER:TARGETED:READ_PROCESSING:MARKDUPS (220024489_220024489)` terminated with an error exit status (1)


Command executed:

  markdups \
      -Xmx36721970381 \
       \
      \
      -samtools $(which samtools) \
      -sambamba $(which sambamba) \
      \
      -sample 220024489 \
      -input_bam 0005.220024489.220024489.UDB-172.L02.bam,0006.220024489.220024489.UDB-172.L02.bam,0004.220024489.220024489.UDB-172.L02.bam,0002.220024489.220024489.UDB-172.L02.bam,0003.220024489.220024489.UDB-172.L02.bam,0001.220024489.220024489.UDB-172.L02.bam \
      \
      -form_consensus \
      -umi_enabled -umi_duplex -umi_duplex_delim + \
      \
      -unmap_regions unmap_regions.38.tsv \
      -ref_genome GCA_000001405.15_GRCh38_no_alt_analysis_set.fna \
      -ref_genome_version 38 \
      \
      -write_stats \
      -threads 6 \
      \
      -output_bam 220024489.markdups.bam
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_ONCOANALYSER:TARGETED:READ_PROCESSING:MARKDUPS":
      markdups: $(markdups -version | awk '{ print $NF }')
      sambamba: $(sambamba --version 2>&1 | egrep '^sambamba' | head -n 1 | awk '{ print $NF }')
      samtools: $(samtools --version 2>&1 | egrep '^samtools\s' | head -n 1 | sed 's/^.* //')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  /usr/local/bin/markdups: line 6: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
  05:47:50.069 [main] [INFO ] MarkDups version 1.1.7
  05:47:50.623 [main] [INFO ] output(./)
  05:47:50.917 [main] [INFO ] loaded 80309 unmapping regions from unmap_regions.38.tsv
  05:47:50.917 [main] [INFO ] duplicate logic: UMIs
  05:47:50.919 [main] [INFO ] sample(220024489) starting mark duplicates
  05:47:52.108 [Thread-5] [ERROR] read(id(F350034942L2C004R01600016485:TGTGTCT_CTACTGT) coords(chr1:5014528-5014620) cigar(93M) mate(chr1:5014615) flags(99)) exception: java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 15
  java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 15
  	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
  	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
  	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
  	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
  	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
  	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
  	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
  	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4914)
  	at java.base/java.lang.String.substring(String.java:2876)
  	at com.hartwig.hmftools.markdups.umi.UmiGroupBuilder.splitUmi(UmiGroupBuilder.java:505)
  	at com.hartwig.hmftools.markdups.umi.UmiGroupBuilder.hasDuplexUmiMatch(UmiGroupBuilder.java:493)
  	at com.hartwig.hmftools.markdups.umi.UmiGroupBuilder.collapseCoordinateGroup(UmiGroupBuilder.java:444)
  	at com.hartwig.hmftools.markdups.umi.UmiGroupBuilder.processUmiGroups(UmiGroupBuilder.java:289)
  	at com.hartwig.hmftools.markdups.common.DuplicateGroupBuilder.processDuplicateGroups(DuplicateGroupBuilder.java:248)
  	at com.hartwig.hmftools.markdups.PartitionReader.accept(PartitionReader.java:357)
  	at com.hartwig.hmftools.markdups.PartitionReader.accept(PartitionReader.java:43)
  	at com.hartwig.hmftools.markdups.ReadPositionsCache.checkFlush(ReadPositionsCache.java:305)
  	at com.hartwig.hmftools.markdups.ReadPositionsCache.storeInitialRead(ReadPositionsCache.java:166)
  	at com.hartwig.hmftools.markdups.ReadPositionsCache.processRead(ReadPositionsCache.java:141)
  	at com.hartwig.hmftools.markdups.PartitionReader.processSamRecord(PartitionReader.java:216)
  	at com.hartwig.hmftools.markdups.BamReader.sliceRegion(BamReader.java:83)
  	at com.hartwig.hmftools.markdups.PartitionReader.processRegion(PartitionReader.java:125)
  	at com.hartwig.hmftools.markdups.PartitionThread.run(PartitionThread.java:61)
```
